### ISSUE TITLE
Unofficial SpaceApps Challenge Forum - STEMN

### ISSUE THREAD

**Issue by joshleeb** [Makris11/spaces-apps#1]
Hey Like-A-Glove Team,

We're a team from Sydney, Australia and we created a Pre-SpaceApps challenge to ourselves. We've created the unofficial Space Apps Challenge Forums! You can find them at https://stemn.com/org/sac. 

We've added a project on STEMN for your Like-A-Glove project. Great name by the way. You can check it out here https://stemn.com/projects/like-a-glove. You can also check out all the discussions related to the Space Glove theme in this thread: https://stemn.com/threads/space-glove-spacecraft-gestures-and-voice-commanding. Make sure you say hi in the thread so you can get to know the other teams in the theme. 

To signup go to https://stemn.com/org/sac. We're currently in closed beta but have decided to give you special access with the signup code at that link. Once you've made an account, or if you have any questions, send me a email at josh@stemn.com and I can transfer the project to your account.

Goodluck this weekend.
See you on STEMN!

**Comment by Makris11** [comment]
Hey Josh 

Great work with the forum, it looks amazing. I've just signed up and my username is "Panagiotis Makris". Good luck with the competition! 

Best Regards 
Panagiotis 

----- Original Message -----
